name: s6trible

services:
  s6trible_DB:
    image: mariadb:10.6
    restart: always
    ports: 
      - 3306:3306
    volumes: 
      - ./db/:/var/lib/mysql
    environment:
      MYSQL_DATABASE: $MYSQL_DATABASE 
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD




